redis:
  image: redis

mongo:
  image: mongo

nginx:
  image: nginx
  links:
    - apogee
    - azkaban
    - bolide
  ports:
    - 80:80
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro

bolide:
  image: madeye/bolide:0.1
  links:
    - redis

azkaban:
  image: madeye/azkaban:0.1
  links:
    - redis
    - mongo

apogee:
  image: madeye/apogee:0.1
  links:
    - azkaban
    - bolide
    - mongo
