#! /usr/bin/env node
fs = require('fs')

var azkabanUrl = "http://" + process.env.AZKABAN_PORT_4004_TCP_ADDR + ":" + process.env.AZKABAN_PORT_4004_TCP_PORT,

settings = {
  public: {
    bolideUrl: "http://" + process.env.BOLIDE_PORT_3003_TCP_ADDR + ":" + process.env.BOLIDE_PORT_3003_TCP_PORT,
    azkabanUrl: azkabanUrl,
    apogeeUrl: process.env.MADEYE_URL,
    hangoutUrl: azkabanUrl + "/hangout/",
    tunnelHost: process.env.MADEYE_TUNNEL_HOST,
    acePrefix: "/packages/reactive-ace/ace-builds/src",
    staticPrefix: "static"
  }
};

fs.writeFileSync(__dirname + '/../settings.json', JSON.stringify(settings));
envVariables = "MONGO_URL=" + process.env.MADEYE_MONGO_URL + "\n"
fs.writeFileSync(__dirname + '/../.env', envVariables);
//stdout used by docker run command
console.log(JSON.stringify(settings));