#! /usr/bin/env node
fs = require('fs')

settings = {
  public: {
    bolideUrl: process.env.MADEYE_BOLIDE_URL,
    azkabanUrl: process.env.MADEYE_AZKABAN_URL,
    apogeeUrl: process.env.MADEYE_APOGEE_URL,
    googleAnalyticsId: process.env.MADEYE_GOOGLE_ANALYTICS_ID,
    boggartUrl: process.env.MADEYE_BOGGART_URL,
    kissMetricsId: process.env.MADEYE_KISS_METRICS_ID,
    nurmengardUrl: process.env.MADEYE_NURMENGARD_URL,
    hangoutUrl: process.env.MADEYE_AZKABAN_URL + "/hangout/",
    shareServer: process.env.MADEYE_SHARE_SERVER
  },
  googleClientId: process.env.MADEYE_GOOGLE_CLIENT_ID,
  googleSecret: process.env.MADEYE_GOOGLE_SECRET

};

fs.writeFileSync(__dirname + '/../settings.json', JSON.stringify(settings));
envVariables = "MONGO_URL=" + process.env.MADEYE_MONGO_URL + "\n"
fs.writeFileSync(__dirname + '/../.env', envVariables);
