#! /usr/bin/env node
fs = require('fs')

settings = {
  public: {
    bolideUrl: process.env.MADEYE_BOLIDE_URL,
    azkabanUrl: process.env.MADEYE_AZKABAN_URL,
    apogeeUrl: process.env.MADEYE_APOGEE_URL,
    googleAnalyticsId: process.env.MADEYE_GOOGLE_ANALYTICS_ID,
    boggartUrl: process.env.MADEYE_BOGGART_URL,
    kissMetricsId: process.env.MADEYE_KISS_METRICS_ID
  }
};

fs.writeFileSync(__dirname + '/../settings.json', JSON.stringify(settings));
envVariables = "MONGO_URL=" + process.env.MADEYE_MONGO_URL + "\n"
fs.writeFileSync(__dirname + '/../.env', envVariables);
